// TODO:MODIFIED BY PLATON
const PLATON_TEST = 'platon_test'
const PLATON_AMIGO = 'platon_amigo'
const PLATON_BATALA = 'platon_batala'

const PLATON_TEST_CODE = 203
const PLATON_AMIGO_CODE = 1
const PLATON_BATALA_CODE = 1

const PLATON_TEST_DISPLAY_NAME = 'Main Platon Test Network'
const PLATON_AMIGO_DISPLAY_NAME = 'PLATON AMIGO Network'
const PLATON_BATALA_DISPLAY_NAME = 'PLATON BATALA Network'

module.exports = {
  PLATON_TEST,
  PLATON_AMIGO,
  PLATON_BATALA,
  PLATON_TEST_CODE,
  PLATON_AMIGO_CODE,
  PLATON_BATALA_CODE,
  PLATON_TEST_DISPLAY_NAME,
  PLATON_AMIGO_DISPLAY_NAME,
  PLATON_BATALA_DISPLAY_NAME,
}
