// TODO:MODIFY BY PLATON
const {
  PLATON_TEST_CODE,
  PLATON_AMIGO_CODE,
  PLATON_BATALA_CODE,
  PLATON_TEST_DISPLAY_NAME,
  PLATON_AMIGO_DISPLAY_NAME,
  PLATON_BATALA_DISPLAY_NAME,
} = require('./enums')

const networkToNameMap = {
  [PLATON_TEST_CODE]: PLATON_TEST_DISPLAY_NAME,
  [PLATON_AMIGO_CODE]: PLATON_AMIGO_DISPLAY_NAME,
  [PLATON_BATALA_CODE]: PLATON_BATALA_DISPLAY_NAME,
}

const getNetworkDisplayName = key => networkToNameMap[key]

module.exports = {
  getNetworkDisplayName,
}
